Use SCCACHE (#28)
* build.sh: Keep script consistency across platforms

* add BUILDDIR across all scripts (ref: .ci/linux/package.sh)
* call cmake from "source" to "build" not from build
* extra parameters direct go direct on cmake (ref: .ci/windows/build.sh)

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] check if Android Keys are set

* this haunted me cause there's no name consistency

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] enable sccache to reduce build time

* should be changed to mozilla-actions/sccache-action
  (or cloned to Eden-CI)
  after they fix aarch64 download
  (the problem is, the fix is already on master, but
  it isn't released basically [dist is outdated])

See:
* https://github.com/Mozilla-Actions/sccache-action/pull/225
* https://github.com/Mozilla-Actions/sccache-action/issues/189

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] android: enable gradle cache (android) + sccache (core)

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] keep consistency across platforms and use CPM_CACHE_VERSION

* keep the same name versioning of cache
* clean solution to purge cache, since we can change varible internal
  without necessity of commit

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] cache installation packages, should reduce 1m?

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] Use parallel to improve building time

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] Enable sccache globally

* this explain why sccache is not working on android

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] cleanup some cache things

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] allow building with debug keys for PRs

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] remove merged patch

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

* [ci] it's if not

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

---------

Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,6 +27,8 @@ on:
 
 env:
   DISABLE_ARM: ${{ vars.DISABLE_ARM }}
+  SCCACHE_GHA_ENABLED: "true"
+  CCACHE: "true"
 
 jobs:
   summary:
@@ -153,17 +155,19 @@ jobs:
     name: "Linux (${{ matrix.os.arch }}) (${{ matrix.compiler }})"
     needs: [set-matrix, clone]
     runs-on: ${{ matrix.os.runs-on }}
+    container: ghcr.io/pkgforge-dev/archlinux:latest
     strategy:
       fail-fast: false
       matrix:
         os: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
         compiler: ${{ fromJson(needs.set-matrix.outputs.compilers) }}
 
-    container: ghcr.io/pkgforge-dev/archlinux:latest
-
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: Install sccache
+        uses: Vee99BR/sccache-action@v0.0.1
 
       - name: Install dependencies
         run: |
@@ -198,14 +202,12 @@ jobs:
           path: |
             ${{ github.workspace }}/.cache
             ${{ github.workspace }}/build/_deps/*-build
-          key: ${{ runner.os }}-${{ matrix.os.arch }}-cpm-v5-${{ github.run_id }}
-          restore-keys: |
-            ${{ runner.os }}-${{ matrix.os.arch }}-cpm-v5-
+          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler }}-cpm-${{ env.CPM_CACHE_VERSION }}
 
       - name: Build
         shell: bash
         run: |
-          TARGET=appimage ./.ci/linux/build.sh ${{ matrix.os.arch }}
+          TARGET=appimage ./.ci/linux/build.sh ${{ matrix.os.arch }} -DCCACHE_PATH=${SCCACHE_PATH}
 
       - name: Package
         shell: bash
@@ -234,9 +236,7 @@ jobs:
   windows:
     name: "Windows ${{ matrix.os.arch }} (${{ matrix.compiler }})"
     needs: [clone]
-    env:
-      QT_VERSION: 6.9.1
-
+    runs-on: ${{ matrix.os.runs-on }}
     strategy:
       fail-fast: false
       matrix:
@@ -246,12 +246,15 @@ jobs:
           - runs-on: windows-11-arm
             arch: arm64
         compiler: [clang, msvc]
-
-    runs-on: ${{ matrix.os.runs-on }}
+    env:
+      QT_VERSION: 6.9.1
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: Install sccache
+        uses: Vee99BR/sccache-action@v0.0.1
 
       - name: Install Qt
         uses: jurplel/install-qt-action@v4.3.0
@@ -287,9 +290,7 @@ jobs:
           path: |
             ${{ github.workspace }}/.cache
             ${{ github.workspace }}/build/_deps/*-build
-          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler }}-unix-cpm-v5-${{ github.run_id }}
-          restore-keys: |
-            ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler }}-unix-cpm-v5-
+          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler }}-cpm-${{ env.CPM_CACHE_VERSION }}
 
       - name: Set up MSVC
         uses: ilammy/msvc-dev-cmd@v1
@@ -315,7 +316,7 @@ jobs:
           git config --global core.autocrlf off
           dos2unix .patch/boost/*
 
-          ./.ci/windows/build.sh
+          ./.ci/windows/build.sh -DCCACHE_PATH=${SCCACHE_PATH}
 
       - name: Package
         shell: bash
@@ -330,13 +331,40 @@ jobs:
           path: artifacts/*
 
   android:
-    runs-on: ubuntu-latest
-    needs: [clone]
     name: "Android"
+    needs: [clone]
+    runs-on: ${{ matrix.os.runs-on }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os:
+          - runs-on: ubuntu-latest
+            arch: amd64
+        compiler: [universal]
 
     steps:
+      - name: Check Android secrets
+        run: |
+          if [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
+            echo "CI_PR_FORK=true" >> $GITHUB_ENV
+          else
+            if [ -z "${ANDROID_KEYSTORE_B64}" ] || \
+               [ -z "${ANDROID_KEY_ALIAS}" ] || \
+               [ -z "${ANDROID_KEYSTORE_PASS}" ]; then
+              echo "::error ::Missing required Android secrets!"
+              exit 1
+            fi
+          fi
+        env:
+          ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
+          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
+          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
+
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: Install sccache
+        uses: Vee99BR/sccache-action@v0.0.1
 
       - name: Install dependencies
         run: |
@@ -354,19 +382,27 @@ jobs:
         with:
           name: eden
 
+      - name: Install gradle-cache
+        uses: burrunan/gradle-cache-action@v3
+        with:
+          job-id: android
+          gradle-version: wrapper
+          save-local-build-cache: true
+          save-gradle-dependencies-cache: true
+          remote-build-cache-proxy-enabled: true
+          build-root-directory: src/android
+
       - name: Set up CPM cache
         uses: actions/cache@v4
         with:
           path: |
             ${{ github.workspace }}/.cache
             ${{ github.workspace }}/build/_deps/*-build
-          key: ${{ runner.os }}-cpm-v5-${{ github.run_id }}
-          restore-keys: |
-            ${{ runner.os }}-cpm-v5-
+          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler }}-cpm-${{ env.CPM_CACHE_VERSION }}
 
       - name: Build
         run: |
-          JAVA_HOME=$JAVA_HOME_17_X64 DEVEL=true ./.ci/android/build.sh
+          JAVA_HOME=$JAVA_HOME_17_X64 DEVEL=true ./.ci/android/build.sh -DCCACHE_PATH=${SCCACHE_PATH}
         env:
           ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
           ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
@@ -389,13 +425,23 @@ jobs:
           path: artifacts/*.aab
 
   macos:
-    runs-on: macos-latest
-    needs: [clone]
     name: "macOS"
+    needs: [clone]
+    runs-on: ${{ matrix.os.runs-on }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os:
+          - runs-on: macos-latest
+            arch: arm64
+        compiler: [universal]
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: Install sccache
+        uses: Vee99BR/sccache-action@v0.0.1
 
       - name: Install dependencies
         run: ./.ci/macos/deps.sh
@@ -432,13 +478,11 @@ jobs:
           path: |
             ${{ github.workspace }}/.cache
             ${{ github.workspace }}/build/_deps/*-build
-          key: ${{ runner.os }}-cpm-v5-${{ github.run_id }}
-          restore-keys: |
-            ${{ runner.os }}-cpm-v5-
+          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler }}-cpm-${{ env.CPM_CACHE_VERSION }}
 
       - name: Build
         run: |
-          ./.ci/macos/build.sh
+          ./.ci/macos/build.sh -DCCACHE_PATH=${SCCACHE_PATH}
 
       - name: Package
         run: |
